# Generated by Django 2.2.7 on 2019-11-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_playerclanwar_final_battles_misses'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoyaleAPIError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clazz', models.CharField(max_length=256, null=True)),
                ('traceback', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(max_length=128, null=True)),
                ('refresh_method', models.CharField(max_length=256, null=True)),
                ('data', models.TextField(null=True)),
                ('code', models.CharField(max_length=64, null=True)),
                ('reason', models.CharField(max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
